[workspace]
resolver = "3"

members = [
    "popgen",
    "python-integration-tests"
]

[workspace.package]
edition = "2021"
rust-version = "1.88.0"

[workspace.dependencies]
tskit = { version = ">=0.16.3" }
rand = "0.9.0"
rand_distr = "0.5.1"
rayon = "1.11.0"
proptest = "1.10.0"

[workspace.lints.rust]
# Added for rust 1.80.0
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(doc_cfg)'] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
lto = "fat"
codegen-units = 1
