[package]
name = "popgen"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14.0"
noodles = { version = "0.92.0", features = ["vcf"], optional = true }
tskit = { version = "0.15.0-alpha.2", optional = true, features=["bindings"] }

[dev-dependencies]
rand = "0.9.0"
noodles-core = "0.16.0"
triangle_matrix = "0.4.0"
noodles = { version = "0.92.0", features = ["vcf", "csi", "tabix"] }

[profile.release]
lto = "fat"

[[test]]
name = "test_try_from_tree_sequence"
path = "tests/test_try_from_tree_sequence.rs"
required-features = ["tskit"]

[[example]]
name = "from_vcf"
required-features = ["noodles"]

[[example]]
name = "from_vcf_indexed"
required-features = ["noodles"]

[[example]]
name = "from_tskit"
required-features = ["tskit"]

