[package]
name = "popgen"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14.0"
noodles = { version = "0.92.0", features = ["vcf"] }

[dev-dependencies]
rand = "0.9.0-alpha.2"
noodles-core = "0.15.0"
triangle_matrix = "0.4.0"
