[package]
name = "popgen"
version = "0.10.0-alpha.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Efficient types for population genetic analysis."
homepage.workspace = true
repository.workspace = true

[dependencies]

[dev-dependencies]
rand = { workspace = true }
rand_distr = { workspace = true }
proptest = { workspace = true }

[lints]
workspace = true
