[package]
name = "popgen"
version = "0.10.0-alpha.0"
edition.workspace = true
rust-version.workspace = true
license = "MIT"
description = "Efficient types for population genetic analysis."
homepage = "https://github.com/ThorntonLab/popgen-oxide"
repository = "https://github.com/ThorntonLab/popgen-oxide"

[dependencies]

[dev-dependencies]
rand = { workspace = true }
rand_distr = { workspace = true }
proptest = { workspace = true }

[lints]
workspace = true
