[package]
name = "popgen-htslib"
version = "0.10.0-alpha.0"
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
popgen = { version = "0.10.0-alpha.0", path = "../popgen" }
rust-htslib = { version = "1.0.0", default-features = false }

[dev-dependencies]

[[example]]
name = "from_vcf_htslib"
