[package]
name = "popgen-tskit"
version = "0.10.0-alpha.0"
edition.workspace = true
rust-version.workspace = true
license = "MIT"
description = "tskit helper utilities for the popgen ecosystem."
homepage = "https://github.com/ThorntonLab/popgen-oxide"
repository = "https://github.com/ThorntonLab/popgen-oxide"

[lints]
workspace = true

[dependencies]
popgen = { version = "0.10.0-alpha.0", path = "../popgen" }
tskit = { workspace = true }

[[example]]
name = "from_tskit"
