[package]
name = "popgen-tskit"
version = "0.10.0-alpha.0"
description = "tskit helper utilities for the popgen ecosystem."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
popgen = { version = "0.10.0-alpha.0", path = "../popgen" }
tskit = { workspace = true }

[[example]]
name = "from_tskit"
