[package]
name = "popgen-oxide"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.17.8"
noodles = { version = "0.83.0", features = ["vcf"] }
popgen = { path = "../popgen" }
itertools = "0.13.0"
